# Generated by Django 4.2.1 on 2023-06-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_app', '0003_stafffavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='shows', to='eo_app.stafffavorite'),
        ),
    ]
