# Generated by Django 4.2.1 on 2023-06-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eo_app', '0005_creatorofmonth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatorOfMonth',
            new_name='CreatorOfTheMonth',
        ),
    ]
