# Generated by Django 4.2.1 on 2023-06-29 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eo_app', '0006_rename_creatorofmonth_creatorofthemonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowOfMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eo_app.show')),
            ],
        ),
    ]
