# Generated by Django 4.2.1 on 2023-06-29 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eo_app', '0007_showofmonth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowOfMonth',
            new_name='InfluentialShows',
        ),
    ]
