# Generated by Django 4.2.1 on 2023-06-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eo_app', '0008_rename_showofmonth_influentialshows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfluentialShows',
            new_name='InfluentialShow',
        ),
    ]
