# Generated by Django 4.2.1 on 2023-06-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_app', '0009_rename_influentialshows_influentialshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
