# Generated by Django 4.2.1 on 2026-04-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_app', '0010_creator_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='tmdb_biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='tmdb_last_fetched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='tmdb_profile_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='tmdb_last_fetched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='tmdb_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='tmdb_poster_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
