# Generated by Django 4.2.1 on 2026-04-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eo_app', '0011_creator_tmdb_biography_creator_tmdb_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='favorites',
        ),
        migrations.AlterUniqueTogether(
            name='creatorofthemonth',
            unique_together={('month', 'year', 'creator')},
        ),
        migrations.AlterUniqueTogether(
            name='influentialshow',
            unique_together={('month', 'year', 'show')},
        ),
    ]
