# Generated by Django 4.2.1 on 2026-04-20 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eo_app', '0012_remove_show_favorites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eo_app.show')),
            ],
            options={
                'ordering': ['-featured_date'],
            },
        ),
    ]
