# Generated by Django 4.2.1 on 2026-04-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eo_app', '0014_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('television', 'Television'), ('writers', 'Writers'), ('craft', 'Craft'), ('industry', 'Industry'), ('pilots', 'Pilots')], default='television', max_length=20),
        ),
    ]
